SPLIT_SCHEMA_ID = "cko8sbczn0002h2dkdaxb5kal"
TEST_SPLIT_ID = "cko8scbz70005h2dkastwhgqt"
TEXT_SCHEMA_ID = "cko8s9r5v0001h2dk9elqdidh"
CAPTURE_DT_SCHEMA_ID = "cko8sdzv70006h2dk8jg64zvb"
EXPECTED_METADATA_SCHEMA_IDS = [
    SPLIT_SCHEMA_ID,
    TEST_SPLIT_ID,
    TEXT_SCHEMA_ID,
    CAPTURE_DT_SCHEMA_ID,
]
CUSTOM_TEXT_SCHEMA_NAME = "custom_text"
