# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Read the docs config file version (Required)
version: 2

# https://github.com/wemake-services/wemake-django-template/blob/master/.readthedocs.yml
build:
  os: ubuntu-lts-latest
  commands:
    - asdf plugin add rye
    - asdf install rye latest
    - asdf global rye latest
    - rye config --set-bool behavior.global-python=true
    - rye config --set-bool behavior.use-uv=true
    - rye sync
    - rye run sphinx-build ./docs $READTHEDOCS_OUTPUT/html

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# Not building additional formats, as PDF build is failing
# formats: 
#   - pdf