name: Labelbox Example Notebook Setup
    
runs:
  steps:
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v2
      with:
        enable-cache: true
    - name: Rye Setup
      shell: bash
      run: |
        rye config --set-bool behavior.use-uv=true
    - name: Environment setup
      working-directory: examples
      shell: bash
      run: | 
        rye sync -f --update-all