name: Labelbox Python SDK Notebooks (Develop)

on:
  push:
    branches: [develop]
    paths:
      - examples/**
  pull_request:
    branches: [develop]
    paths:
      - examples/**

permissions:
  contents: write
  pull-requests: write
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Install databooks
        run: sudo pip3 install databooks
      - name: Remove notebook metadata
        run: echo "y" | databooks meta examples/. --rm-outs
      - name: Commit changes
        run: |
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add examples/.
            git commit -m "Removed metadata" || exit 0
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
