name: Labelbox Python SDK Notebooks (Develop)

on:
  push:
    branches: [develop]
    paths:
      - examples/**
  pull_request:
    branches: [develop]
    paths:
      - examples/**

jobs:
  env:
    BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Install databooks
        run: sudo pip3 install databooks
      - name: Remove notebook metadata
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
        run: databooks meta examples/. --rm-outs | echo Y
      - name: Modify and commit changes
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
        run: |
        git add examples/.
        git commit -m "Removed metadata"
        git push
