name: Labelbox Python SDK Shared

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      api-key:
        required: true
        type: string
      da-test-key:
        required: true
        type: string
      test-env:
        required: true
        type: string
      fixture-profile: 
        required: true
        type: boolean

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_ACCESS_TOKEN  }}
          ref: ${{ github.head_ref }}
      - uses: ./.github/actions/python-package-shared-setup
        with:
          rye-version: ${{ vars.RYE_VERSION }}
          python-version: ${{ inputs.python-version }}
      - name: Linting
        working-directory: libs/labelbox
        run: rye run lint
  integration:
    runs-on: ubuntu-latest
    concurrency:
      group: labelbox-python-${{ inputs.test-env }}-${{ inputs.python-version }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_ACCESS_TOKEN  }}
          ref: ${{ github.head_ref }}
      - uses: ./.github/actions/python-package-shared-setup
        with:
          rye-version: ${{ vars.RYE_VERSION }}
          python-version: ${{ inputs.python-version }}
      - name: Integration Testing
        env:
          PYTEST_XDIST_AUTO_NUM_WORKERS: 32
          LABELBOX_TEST_API_KEY: ${{ secrets[inputs.api-key] }}
          DA_GCP_LABELBOX_API_KEY: ${{ secrets[inputs.da-test-key] }}
          LABELBOX_TEST_ENVIRON: ${{ inputs.test-env }}
        working-directory: libs/labelbox
        run: rye run integration
  unit-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_ACCESS_TOKEN  }}
          ref: ${{ github.head_ref }}
      - uses: ./.github/actions/python-package-shared-setup
        with:
          rye-version: ${{ vars.RYE_VERSION }}
          python-version: ${{ inputs.python-version }}
      - name: Unit && Data Testing
        env:
          PYTEST_XDIST_AUTO_NUM_WORKERS: 32
          LABELBOX_TEST_API_KEY: ${{ secrets[inputs.api-key] }}
          DA_GCP_LABELBOX_API_KEY: ${{ secrets[inputs.da-test-key] }}
          LABELBOX_TEST_ENVIRON: ${{ inputs.test-env }}
        working-directory: libs/labelbox
        run: |
          rye sync -f --features labelbox/data
          rye run unit
          rye run data 