name: Labelbox Python SDK Develop

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 3.8
            api-key: STAGING_LABELBOX_API_KEY_2
            da-test-key: DA_GCP_LABELBOX_API_KEY
          - python-version: 3.9
            api-key: STAGING_LABELBOX_API_KEY_3
            da-test-key: DA_GCP_LABELBOX_API_KEY
          - python-version: "3.10"
            api-key: STAGING_LABELBOX_API_KEY_4
            da-test-key: DA_GCP_LABELBOX_API_KEY
          - python-version: 3.11
            api-key: STAGING_LABELBOX_API_KEY
            da-test-key: DA_GCP_LABELBOX_API_KEY
          - python-version: 3.12
            api-key: STAGING_LABELBOX_API_KEY_5
            da-test-key: DA_GCP_LABELBOX_API_KEY
    uses: ./.github/workflows/python-package-shared.yml
    with:
      python-version: ${{ matrix.python-version }}
      api-key: ${{ matrix.api-key }}
      da-test-key: ${{ matrix.da-test-key }}
      fixture-profile: true
      test-env: 'staging'
    secrets: inherit