name: ReadMe GitHub Action 🦉

on:
  push:
    branches: [develop]
    paths:
      - examples/README.md
  pull_request:
    branches: [develop]
    paths:
      - examples/README.md

jobs:
  custompages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/notebooks
      - name: Create readme
        working-directory: examples
        run: rye run create-doc-readme
      - name: Run `custompages` command
        uses: readmeio/rdme@v8
        with:
          rdme: custompages examples/tutorials.html --key=${{ secrets.README_API_KEY }}
