name: ReadMe GitHub Action 🦉

on:
  pull_request:
    branches: [develop]
    types:
      - closed
    paths:
      - examples/README.md

jobs:
  custompages:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-package-shared-setup
        with:
          rye-version: 0.33.0
          python-version: 3.8
      - name: Create readme
        working-directory: examples
        run: rye run create-doc-readme
      - name: Run `custompages` command
        uses: readmeio/rdme@v8
        with:
          rdme: custompages examples/tutorials.html --key=${{ secrets.README_API_KEY }}
