# ref: https://github.com/marketplace/actions/build-and-push-docker-images

name: Release container image

on:
  release:
    types: [published]

env:
  CONTAINER_IMAGE: "ghcr.io/${{ github.repository }}"

jobs:
  context:
    runs-on: ubuntu-latest

    steps:
    - name: downcase CONTAINER_IMAGE
      run: |
        echo "CONTAINER_IMAGE=${CONTAINER_IMAGE,,}" >> ${GITHUB_ENV}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push: true

        platforms: |
          linux/amd64
          linux/arm64

        tags: |
          ${{ env.CONTAINER_IMAGE }}:latest
          ${{ env.CONTAINER_IMAGE }}:${{ github.event.release.tag_name }}
