name: Secret_Scan

on:
  pull_request:

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@6c64db94d5b2e09d7e0948fb6bd3166cc6fffbc7 # main
      with:
        extra_args: --only-verified
