# ref: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

name: Testing container image

on:
  push:
    branches:
      - 'develop'

jobs:
  context:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push: true

        registry: ghcr.io
        organization: "${{ github.event.repository.owner.login }}"
        repository: "${{ github.event.repository.name }}"

        platforms: |
          linux/amd64
          linux/arm64
          darwin/amd64
          darwin/arm64

        tags: |
          develop
          ${{ github.sha }}

        outputs: |
          image: ${{ steps.build.outputs.imageid }}
          digest: ${{ steps.build.outputs.digest }}
          metadata: ${{ steps.build.outputs.metadata }}
